# -*- coding: utf-8 -*-
"""TemperaturaItalia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KJoSPZCFR9eES_K3ZhKGln2OeaSyNz6X
"""

import pandas as pd
import numpy as np
import seaborn as sns
import datetime
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

"""https://power.larc.nasa.gov/data-access-viewer/"""

TempIta = pd.read_csv('gdrive/My Drive/DataAnalysis/TemperaturaItalia/TemperaturaItalia_1981_2021.csv',delimiter=',')

from google.colab import drive 
drive.mount('/content/gdrive')

TempIta

TempIta.dtypes

SoloTemp=TempIta.loc[TempIta['PARAMETER'] == 'TS']
SoloTemp

sns.relplot(data=SoloTemp,x='YEAR',y=['JAN','FEB'],height=6, aspect=3,kind='line')

f = plt.figure()
f.set_figwidth(30)
f.set_figheight(10)

plt.plot(SoloTemp['YEAR'], SoloTemp['JAN'], label="JAN")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['JAN'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['FEB'], label="FEB")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['FEB'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['MAR'], label="MAR")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['MAR'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['APR'], label="APR")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['APR'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['MAY'], label="MAY")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['MAY'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['JUN'], label="JUN")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['JUN'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['JUL'], label="JUL")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['JUL'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['AUG'], label="AUG")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['AUG'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['SEP'], label="SEP")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['SEP'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['OCT'], label="OCT")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['OCT'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['NOV'], label="NOV")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['NOV'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['DEC'], label="DEC")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['DEC'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.legend(loc="upper left")

plt.show()

f = plt.figure()
f.set_figwidth(30)
f.set_figheight(10)

plt.plot(SoloTemp['YEAR'], SoloTemp['FEB'], label="FEB")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['FEB'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['APR'], label="APR")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['APR'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['JUL'], label="JUL")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['JUL'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.plot(SoloTemp['YEAR'], SoloTemp['SEP'], label="SEP")
X = np.array(SoloTemp['YEAR'])
Y = np.array(SoloTemp['SEP'])
X = X.reshape((-1, 1))
model = LinearRegression().fit(X, Y)
plt.plot(X, model.predict(X),color='k')

plt.legend(loc="upper left")

plt.show()